### ISSUE TITLE
Altera virtual JTAG interface

### ISSUE THREAD

**Issue by lapnd** [RoaLogic/adv_dbg_if#4]
Hi,
As in the project status: "Core is up and running, happily debugging RISC-V. Tested in HW on an Altera development board (using the Altera virtual JTAG interface)"
Do you have link/few notes... on how to try this with Altera board?
I would like to try with DE10Lite board where only single USB cable can be used as programming interface as well as debugging the app run on the core.

**Comment by rherveille** [comment]
If you specify Altera for Technology, then the virtual JTAG port will be instantiated.

VirtualJTAG uses USER0 and USER1 registers to implement VIR (Virtual Instruction) and VDR (Virtual Data) registers.

It enables user modules to use the device JTAG port

 

Richard

 

 

Richard Herveille

Managing Director

Phone +31 (45) 405 5681

Cell +31 (6) 5207 2230

***@***.***

 

 

 

On 25/12/2021, 17:19, "lapnd" ***@***.***> wrote:

 

Hi,
As in the project status: "Core is up and running, happily debugging RISC-V. Tested in HW on an Altera development board (using the Altera virtual JTAG interface)"
Do you have link/few notes... on how to try this with Altera board?
I would like to try with DE10Lite board where only single USB cable can be used as programming interface as well as debugging the app run on the core.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
